kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: api-deployment
spec:
  selector:
    matchLabels:
      app: pod-api
      role: api
  replicas: 2
  template:
    metadata:
      name: api-deployment
      labels:
        app: pod-api
        role: api
    spec:
      containers:
        - name: node-app
          image: gcr.io/gcr-project/sample:1.0.0
          env:
            - name: MONGOLAB_URI
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: MONGOLAB_URI
          resources:
            limits:
              memory: "500Mi"
              cpu: "250m"
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /
              port: 3000
          ports:
            - name: http
              containerPort: 3000